# -*- coding: utf-8 -*-

"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pv6p9qMdCGoVC3gj4zuwRwWCdLdMRSj8
"""

import streamlit as st
import requests
from datetime import datetime

st.set_page_config(page_title="Global Weather Dashboard", page_icon="☀️", layout="centered")

st.title("🌍 Global Weather Dashboard")

city = st.text_input("Enter a city name", "London")

if city:
    api_key = "3fc7b6bad318fc2a564e657505e9f501"  # Replace this with your OpenWeather API key
    url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}&units=metric"

    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        weather = data["weather"][0]["main"]
        description = data["weather"][0]["description"].title()
        icon = data["weather"][0]["icon"]
        temp = data["main"]["temp"]
        humidity = data["main"]["humidity"]
        wind = data["wind"]["speed"]
        country = data["sys"]["country"]
        dt = datetime.utcfromtimestamp(data["dt"]).strftime('%Y-%m-%d %H:%M:%S')

        st.markdown(f"### 📍 {city.title()}, {country}")
        st.image(f"http://openweathermap.org/img/wn/{icon}@2x.png", width=100)
        st.write(f"**Condition**: {description}")
        st.write(f"**Temperature**: {temp} °C")
        st.write(f"**Humidity**: {humidity}%")
        st.write(f"**Wind Speed**: {wind} m/s")
        st.write(f"**Last Updated**: {dt} UTC")

    else:
        st.error("City not found. Please check the name.")